In [1]:
import numpy as np
np.random.rand(5)


array([0.57759043, 0.63074685, 0.89722642, 0.90655074, 0.79677565])

In [2]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [3]:
np.random.randint(0,100,(3,2))

array([[16, 54],
       [35, 80],
       [96, 10]])

In [6]:
np.ones((12,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
arr = np.arange(0,100,2)
arr = arr.reshape((5,10))
arr.shape

(5, 10)

In [18]:
rand_arr = np.arange(0,100,3)
rand_arr.max()
rand_arr.argmax()

33

Create an array of 10 zeroes

In [23]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Create an array of 10 ones

In [24]:
arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Create an array 10 fives

In [26]:
arr = np.ones(10)*5
print(arr)
arr = np.zeroes(10)+5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Create an array of Integers from 10 to 50

In [27]:
arr = np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


Create an array of even integers from 10 to 50

In [28]:
arr= np.arange(10,51,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


Create a 3x3 matrix with values ranging from 0 to 8

In [35]:
arr = np.arange(0,9).reshape((3,3))
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Create a 3x3 Identity matrix 

In [37]:
arr = np.eye(3) #since an identity matrix is already a square hence rows and columns would be equal
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Use NumPy to generate a random number between 0 and 1

In [43]:
arr = np.random.rand()
print(arr)


0.8991477107696771


Use NumPy to generate an array of 25 random numbers sampled from  a standard normal distribution

In [44]:
arr = np.random.randn(25)
print(arr)

[-0.29755342  1.2387352   2.44102632 -1.59931609  0.92810577 -0.51930644
 -0.52141095 -1.79723279 -0.9736431   0.25129254  0.88584711  0.17384079
 -0.54702199 -0.89322081 -0.20840102 -0.05932125 -1.57892623  1.15790919
 -2.22137156  0.76608293  0.02364205  0.14911662  0.6163559   0.17036934
 -1.46418734]


Create the given matrix

In [50]:
arr = np.arange(1,101).reshape(10,10)/100
print(arr)
#another way using linspace
arr= np.linspace(0.01, 1, 100).reshape(10,10)
print(arr)


[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]
[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.8

Create an array of 20 linerly space points between 0 and 1:

In [51]:
arr = np.linspace(0,1,20)
print(arr)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


**Numpy Indexing and Selection**

In [52]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [57]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [58]:
mat[3,4]

20

In [59]:
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [61]:
mat[0:3,1:2 ]

array([[ 2],
       [ 7],
       [12]])

In [62]:
mat[4:,]

array([[21, 22, 23, 24, 25]])

In [63]:
mat[3:,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Numpy Operations

In [64]:
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [65]:
mat.sum()

325

Get the standard deviation of the values in mat

In [66]:
mat.std()

7.211102550927978

Get the sum of all columns in mat

In [68]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])